#cloud-config
package_update: true
package_upgrade: false

ssh_pwauth: true
disable_root: false

runcmd:
  - touch /home/ubuntu/.hushlogin
  - chown ubuntu.ubuntu /home/ubuntu/.hushlogin
  - unlink /etc/resolv.conf
  - echo "search rdulinux.com\nnameserver 192.168.2.5" > /etc/resolv.conf
  - echo "alias k='kubectl'" >> /root/.bashrc
  - echo "alias k='kubectl'" >> /home/ubuntu/.bashrc

  - swapoff -a
  - sed -i '/swap/d' /etc/fstab

  - echo  "overlay\nbr_netfilter"  > /etc/modules-load.d/k8s.conf
  - modprobe overlay
  - modprobe br_netfilter

  - echo "net.bridge.bridge-nf-call-iptables=1\nnet.bridge.bridge-nf-call-ip6tables=1\nnet.ipv4.ip_forward=1" > /etc/sysctl.d/k8s.conf
  - sysctl --system

  - apt-get update && apt-get install -y containerd apt-transport-https ca-certificates curl gpg

  - mkdir -p /etc/containerd
  - containerd config default > /etc/containerd/config.toml
  - sed -i 's/SystemdCgroup = false/SystemdCgroup = true/' /etc/containerd/config.toml
  - systemctl restart containerd
  - systemctl enable containerd

  - curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes.gpg
  - echo "deb [signed-by=/etc/apt/keyrings/kubernetes.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /" | sudo tee /etc/apt/sources.list.d/kubernetes.list

  - apt-get update && apt-get install -y kubelet kubeadm kubectl
  - apt-mark hold kubelet kubeadm kubectl

  - echo "net.ipv4.ip_forward = 1" | sudo tee /etc/sysctl.d/99-kubernetes-ipforward.conf
  - sysctl --system

  # kubeadm init
  - a=$(curl -s http://169.254.169.254/latest/meta-data/local-ipv4)
  - b=$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4)
  - kubeadm init --control-plane-endpoint $b:6443 --apiserver-advertise-address=$a --pod-network-cidr=192.168.0.0/16 --cri-socket unix:///run/containerd/containerd.sock
    #- kubeadm init --control-plane-endpoint controller.rdulinux.com --pod-network-cidr=192.168.0.0/16 --cri-socket unix:///run/containerd/containerd.sock

  - mkdir -p /home/ubuntu/.kube /root/.kube
  - cp /etc/kubernetes/admin.conf /home/ubuntu/.kube/config
  - cp /etc/kubernetes/admin.conf /root/.kube/config
  - chown ubuntu:ubuntu /home/ubuntu/.kube/config
  - chown root:root   /root/.kube/config

  - |
    cat <<EOF >/etc/crictl.yaml
    runtime-endpoint: unix:///run/containerd/containerd.sock
    image-endpoint: unix:///run/containerd/containerd.sock
    timeout: 10
    debug: false
    EOF

  # install calico
  - su ubuntu -c "kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.28.0/manifests/calico.yaml"
  - su ubuntu -c "kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml"

  # save join command
  - kubeadm token create --print-join-command > /home/ubuntu/join.sh
    #- chmod +x /home/ubuntu/join.sh
