#cloud-config
package_update: true
package_upgrade: false

runcmd:
  - unlink /etc/resolv.conf
  - echo "search rdulinux.com\nnameserver 192.168.2.5" > /etc/resolv.conf
  - swapoff -a
  - sed -i '/swap/d' /etc/fstab

  - echo  "overlay\nbr_netfilter"  > /etc/modules-load.d/k8s.conf
  - modprobe overlay
  - modprobe br_netfilter

  - echo "net.bridge.bridge-nf-call-iptables=1\nnet.bridge.bridge-nf-call-ip6tables=1\nnet.ipv4.ip_forward=1" > /etc/sysctl.d/k8s.conf
  - sysctl --system
  - apt-get update && apt-get install -y containerd apt-transport-https ca-certificates curl

  - mkdir -p /etc/containerd
  - containerd config default > /etc/containerd/config.toml
  - sed -i 's/SystemdCgroup = false/SystemdCgroup = true/' /etc/containerd/config.toml
  - systemctl restart containerd
  - systemctl enable containerd

  - curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes.gpg
  - echo "deb [signed-by=/etc/apt/keyrings/kubernetes.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /" | sudo tee /etc/apt/sources.list.d/kubernetes.list
  - apt-get update && apt-get install -y kubelet kubeadm kubectl
  - apt-mark hold kubelet kubeadm kubectl
  - echo "net.ipv4.ip_forward = 1" | sudo tee /etc/sysctl.d/99-kubernetes-ipforward.conf
  - sysctl --system
  # kubeadm init
  - sudo kubeadm init --control-plane-endpoint master.rdulinux.com --pod-network-cidr=10.244.0.0/16

  - mkdir -p /home/ubuntu/.kube
  - cp /etc/kubernetes/admin.conf /home/ubuntu/.kube/config
  - chown ubuntu:ubuntu /home/ubuntu/.kube/config

  # install flannel CNI
  - su ubuntu -c "kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml"

  # save join command
  - kubeadm token create --print-join-command > /home/ubuntu/join.sh
  - chmod +x /home/ubuntu/join.sh
