#cloud-config
package_update: true
package_upgrade: false

runcmd:
  - sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config.d/60-cloudimg-settings.conf
  - sed -i 's/^#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
  - rm -fv /root/.ssh/authorized_keys
  - systemctl restart sshd
  - echo -e 'master\nmaster' | passwd root
  - echo -e 'master\nmaster' | passwd ubuntu
  - touch /home/ubuntu/.hushlogin
  - unlink /etc/resolv.conf
  - echo "search rdulinux.com\nnameserver 192.168.2.5" > /etc/resolv.conf

  - swapoff -a
  - sed -i '/swap/d' /etc/fstab

  - apt-get update && apt-get install -y containerd apt-transport-https ca-certificates curl gpg
  - mkdir -p /etc/containerd
  - containerd config default > /etc/containerd/config.toml
  - sed -i 's/SystemdCgroup = false/SystemdCgroup = true/' /etc/containerd/config.toml
  - systemctl restart containerd

  - curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes.gpg
  - echo "deb [signed-by=/etc/apt/keyrings/kubernetes.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /" | sudo tee /etc/apt/sources.list.d/kubernetes.list

  - apt-get update && apt-get install -y kubelet kubeadm kubectl
  - apt-mark hold kubelet kubeadm kubectl

  - echo "net.ipv4.ip_forward = 1" | sudo tee /etc/sysctl.d/99-kubernetes-ipforward.conf
  - sysctl --system

  # auto join the cluster
  #- bash /home/ubuntu/join.sh || true
